# -*- coding: utf-8 -*-
"""class on dictionaries(16/06/2025)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMMBZs3NbC4P_WuK6OKSQTlx_vT2ddoe
"""

dict1 = {
1:{2:"Hello"},
3:{4:"what"}
}
res1 = dict1.get(1)
print(res1.get(2))

'''Q9. Find Topper in Each Subject
Description: Return the name of the student with the highest score in each subject.

python

data = {
  'Riya': {'Math': 87, 'English': 78},
  'Ankit': {'Math': 92, 'English': 85},
  'Meena': {'Math': 85, 'English': 88}
}

Output:
{'Math': 'Ankit', 'English': 'Meena'}'''

result={}
data = {
  'Riya': {'Math': 87, 'English': 78},
  'Ankit': {'Math': 92, 'English': 85},
  'Meena': {'Math': 85, 'English': 88}
}
m_max=0
m_name=''
e_name=''
e_max=0
for i in data:
  marks=data.get(i)
  if marks['Math']>=m_max:
    m_max=marks['Math']
    m_name=i
  if marks['English']>=e_max:
    e_max=marks['English']
    e_name=i
result['Math']=m_name
result['English']=e_name
print(result)

'''Q1. Group Employees by Department
Description: Given employee records, group them by department.
python
CopyEdit
Input:
data = {
  'emp1': {'name': 'Alice', 'dept': 'HR', 'salary': 50000},
  'emp2': {'name': 'Bob', 'dept': 'IT', 'salary': 60000},
  'emp3': {'name': 'Charlie', 'dept': 'HR', 'salary': 55000},
  'emp4': {'name': 'David', 'dept': 'IT', 'salary': 70000}
}

Output:
{
  'HR': ['Alice', 'Charlie'],
  'IT': ['Bob', 'David']
}'''

data = {
  'emp1': {'name': 'Alice', 'dept': 'HR', 'salary': 50000},
  'emp2': {'name': 'Bob', 'dept': 'IT', 'salary': 60000},
  'emp3': {'name': 'Charlie', 'dept': 'HR', 'salary': 55000},
  'emp4': {'name': 'David', 'dept': 'IT', 'salary': 70000}
}

departments=[]
result={}
for emp_id, details in data.items():
  dept = details['dept']
  name = details['name']
  if dept not in result:
    result[dept]=[]
  result[dept].append(name)
print(result)

'''Input:
data = {
  'p1': {'vendor': 'Amazon', 'product': 'Laptop'},
  'p2': {'vendor': 'Flipkart', 'product': 'Shoes'},
  'p3': {'vendor': 'Amazon', 'product': 'Mouse'},
  'p4': {'vendor': 'Amazon', 'product': 'Keyboard'},
  'p5': {'vendor': 'Flipkart', 'product': 'Watch'}
}'''

data = {
  'p1': {'vendor': 'Amazon', 'product': 'Laptop'},
  'p2': {'vendor': 'Flipkart', 'product': 'Shoes'},
  'p3': {'vendor': 'Amazon', 'product': 'Mouse'},
  'p4': {'vendor': 'Amazon', 'product': 'Keyboard'},
  'p5': {'vendor': 'Flipkart', 'product': 'Watch'}
}
sellers={}
count={}

for p,details in data.items():
  if details['vendor'] not in sellers:
    sellers[details['vendor']]=[]
    count[details['vendor']]=0
  sellers[details['vendor']].append(details['product'])
  count[details['vendor']]+=1
cmax=0
#print(count)
for ven, c in count.items():
  if c>cmax:
    cmax=c
    ven_name=ven


price_data = {
    'Laptop': 60000,
    'Shoes': 3000,
    'Mouse': 800,
    'Keyboard': 1500,
    'Watch': 2500
}
#print(sellers[ven_name])
s={}
for i in sellers[ven_name]:
  s[i]=price_data[i]
result={ven_name:s}
print(result)

'''Q9. Convert Nested Dict to Flat Dict
python
CopyEdit
nested = {'John': {'Math': 80, 'Sci': 90}, 'Alice': {'Math': 85, 'Sci': 92}}

# Output:
# {'John_Math': 80, 'John_Sci': 90, 'Alice_Math': 85, 'Alice_Sci': 92}'''


result={}
nested = {'John': {'Math': 80, 'Sci': 90}, 'Alice': {'Math': 85, 'Sci': 92}}
for key,value in nested.items():
  for sub, marks in value.items():
    name=key+'_'+sub
    result[name]=marks
print(result)