# -*- coding: utf-8 -*-
"""HW2(17-06-2025).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z4riUViuAXanLuEO-etiQnEB3_3NdhCs
"""

#done
'''Q1. Join Products with Prices and Vendors
Description: Merge product details from products, prices, and vendors dictionaries using product_id.

products = {
  'p1': {'name': 'Laptop', 'vendor_id': 'v1'},
  'p2': {'name': 'Shoes', 'vendor_id': 'v2'},
  'p3': {'name': 'Watch', 'vendor_id': 'v2'}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Flipkart'
}
prices = {
  'p1': 60000,
  'p2': 2500,
  'p3': 3500
}

Output:
{
  'p1': {'name': 'Laptop', 'vendor': 'Amazon', 'price': 60000},
  'p2': {'name': 'Shoes', 'vendor': 'Flipkart', 'price': 2500},
  'p3': {'name': 'Watch', 'vendor': 'Flipkart', 'price': 3500}'''

result={}
products = {
  'p1': {'name': 'Laptop', 'vendor_id': 'v1'},
  'p2': {'name': 'Shoes', 'vendor_id': 'v2'},
  'p3': {'name': 'Watch', 'vendor_id': 'v2'}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Flipkart'
}
prices = {
  'p1': 60000,
  'p2': 2500,
  'p3': 3500
}

for p,info in products.items():
  info2={}
  info2['name']=info['name']
  info2['vendor']=vendors[info['vendor_id']]
  info2['price']=prices[p]
  result[p]=info2
print(result)

#done
'''Q2. List All Products with Category Name
products = {
  'p1': {'name': 'Laptop', 'category_id': 'c1'},
  'p2': {'name': 'Shirt', 'category_id': 'c2'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Clothing'
}

Output:
{
  'p1': {'name': 'Laptop', 'category': 'Electronics'},
  'p2': {'name': 'Shirt', 'category': 'Clothing'}
}'''

products = {
  'p1': {'name': 'Laptop', 'category_id': 'c1'},
  'p2': {'name': 'Shirt', 'category_id': 'c2'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Clothing'
}
result={}
for p,info in products.items():
  info2={}
  info2['name']=info['name']
  info2['category']=categories[info['category_id']]
  result[p]=info2
print(result)

#done
'''Q3. Count Products per Vendor
products = {
  'p1': {'name': 'Mouse', 'vendor_id': 'v1'},
  'p2': {'name': 'Keyboard', 'vendor_id': 'v1'},
  'p3': {'name': 'Bag', 'vendor_id': 'v2'}
}

Output:
{
  'v1': 2,
  'v2': 1
}'''
products = {
  'p1': {'name': 'Mouse', 'vendor_id': 'v1'},
  'p2': {'name': 'Keyboard', 'vendor_id': 'v1'},
  'p3': {'name': 'Bag', 'vendor_id': 'v2'}
}
result={}
for p,info in products.items():
  v=info['vendor_id']
  if v not in result.keys():
    result[v]=1
  else:
    result[v]+=1
print(result)

#done
'''Q4. Average Price per Vendor
products = {
  'p1': {'vendor_id': 'v1', 'price': 1000},
  'p2': {'vendor_id': 'v1', 'price': 2000},
  'p3': {'vendor_id': 'v2', 'price': 3000}
}

Output:
{
  'v1': 1500.0,
  'v2': 3000.0
}'''
result={}
res={}
products = {
  'p1': {'vendor_id': 'v1', 'price': 1000},
  'p2': {'vendor_id': 'v1', 'price': 2000},
  'p3': {'vendor_id': 'v2', 'price': 3000}
}
count={}
for p,details in products.items():
  v=details['vendor_id']
  if v not in result:
    result[v]=details['price']
    count[v]=1
  else:
    result[v]+=details['price']
    count[v]+=1
for v in result.keys():
  res[v]=result[v]/count[v]
print(res)

#done
'''Q5. List Products Belonging to Electronics Category
products = {
  'p1': {'name': 'Mouse', 'category_id': 'c1'},
  'p2': {'name': 'Shirt', 'category_id': 'c2'},
  'p3': {'name': 'Laptop', 'category_id': 'c1'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Clothing'
}

Output:
['Mouse', 'Laptop']'''

gadgets=[]
products = {
  'p1': {'name': 'Mouse', 'category_id': 'c1'},
  'p2': {'name': 'Shirt', 'category_id': 'c2'},
  'p3': {'name': 'Laptop', 'category_id': 'c1'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Clothing'
}

for c,cat in categories.items():
  if cat=='Electronics':
    c_f=c
    break
for p, info in products.items():
  if info['category_id']==c_f:
    gadgets.append(info['name'])
print(gadgets)

#done
'''Q6. Create Vendor-Product Mapping
products = {
  'p1': {'name': 'Laptop', 'vendor_id': 'v1'},
  'p2': {'name': 'Shoes', 'vendor_id': 'v2'},
  'p3': {'name': 'Phone', 'vendor_id': 'v1'}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Flipkart'
}

Output:
{
  'Amazon': ['Laptop', 'Phone'],
  'Flipkart': ['Shoes']
}'''

products = {
  'p1': {'name': 'Laptop', 'vendor_id': 'v1'},
  'p2': {'name': 'Shoes', 'vendor_id': 'v2'},
  'p3': {'name': 'Phone', 'vendor_id': 'v1'}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Flipkart'
}
result={}
for p, details in products.items():
  if vendors[details['vendor_id']] not in result.keys():
    result[vendors[details['vendor_id']]]=[details['name']]
  else:
    result[vendors[details['vendor_id']]].append(details['name'])
print(result)

#done
'''Q7. Filter Products > ₹3000 and Show Vendor Name
products = {
  'p1': {'name': 'Watch', 'vendor_id': 'v1', 'price': 4000},
  'p2': {'name': 'Book', 'vendor_id': 'v2', 'price': 500},
  'p3': {'name': 'Tablet', 'vendor_id': 'v1', 'price': 7000}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Bookstore'
}

Output:
[
  {'name': 'Watch', 'vendor': 'Amazon', 'price': 4000},
  {'name': 'Tablet', 'vendor': 'Amazon', 'price': 7000}
]'''

products = {
  'p1': {'name': 'Watch', 'vendor_id': 'v1', 'price': 4000},
  'p2': {'name': 'Book', 'vendor_id': 'v2', 'price': 500},
  'p3': {'name': 'Tablet', 'vendor_id': 'v1', 'price': 7000}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Bookstore'
}
result=[]
for p,details in products.items():
  if details['price']>3000:
    r={}
    r['name']=details['name']
    r['vendor']=vendors[details['vendor_id']]
    r['price']=details['price']
    result.append(r)
print(result)

#done
'''Q8. Show Category-wise Product Count
products = {
  'p1': {'category_id': 'c1'},
  'p2': {'category_id': 'c2'},
  'p3': {'category_id': 'c1'},
  'p4': {'category_id': 'c3'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Clothing',
  'c3': 'Home Decor'
}

Output:
{
  'Electronics': 2,
  'Clothing': 1,
  'Home Decor': 1
}'''

products = {
  'p1': {'category_id': 'c1'},
  'p2': {'category_id': 'c2'},
  'p3': {'category_id': 'c1'},
  'p4': {'category_id': 'c3'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Clothing',
  'c3': 'Home Decor'
}
result={}
for p,details in products.items():
  if categories[details['category_id']] not in result.keys():
    result[categories[details['category_id']]]=1
  else:
    result[categories[details['category_id']]]+=1
print(result)

#done
'''Q9. Enrich Orders with Product and Vendor Info
orders = {
  'o1': {'product_id': 'p1'},
  'o2': {'product_id': 'p2'}
}
products = {
  'p1': {'name': 'TV', 'vendor_id': 'v1'},
  'p2': {'name': 'Shirt', 'vendor_id': 'v2'}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Flipkart'
}

Output:
{
  'o1': {'product': 'TV', 'vendor': 'Amazon'},
  'o2': {'product': 'Shirt', 'vendor': 'Flipkart'}
}'''

orders = {
  'o1': {'product_id': 'p1'},
  'o2': {'product_id': 'p2'}
}
products = {
  'p1': {'name': 'TV', 'vendor_id': 'v1'},
  'p2': {'name': 'Shirt', 'vendor_id': 'v2'}
}
vendors = {
  'v1': 'Amazon',
  'v2': 'Flipkart'
}
result={}

for o, details in orders.items():
  final={}
  final['product']=(products[details['product_id']])['name']
  final['vendor']=vendors[products[details['product_id']]['vendor_id']]
  result[o]=final
print(result)

#done
'''Q10. Match Inventory to Product Price and Category
inventory = {
  'p1': {'stock': 10},
  'p2': {'stock': 5}
}
products = {
  'p1': {'name': 'Phone', 'price': 15000, 'category_id': 'c1'},
  'p2': {'name': 'Mixer', 'price': 3000, 'category_id': 'c2'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Home Appliance'
}

Output:
{
  'p1': {'name': 'Phone', 'stock': 10, 'price': 15000, 'category': 'Electronics'},
  'p2': {'name': 'Mixer', 'stock': 5, 'price': 3000, 'category': 'Home Appliance'}
}'''
result={}
inventory = {
  'p1': {'stock': 10},
  'p2': {'stock': 5}
}
products = {
  'p1': {'name': 'Phone', 'price': 15000, 'category_id': 'c1'},
  'p2': {'name': 'Mixer', 'price': 3000, 'category_id': 'c2'}
}
categories = {
  'c1': 'Electronics',
  'c2': 'Home Appliance'
}
for p, details in inventory.items():
  result[p]=details

for p, details in products.items():
  result[p]['name']=details['name']
  result[p]['price']=details['price']
  result[p]['category']=categories[details['category_id']]
print(result)